"""Generated advisory snapshot. Do not edit by hand."""

ADVISORY_SNAPSHOT = '2026-07-02'
TRACKED_CVE_COUNT = 543
ADVISORIES = [{'ghsa': 'GHSA-w4v6-g3wm-w36c',
  'cve': None,
  'severity': 'CRITICAL',
  'cvss': 9.3,
  'title': 'OpenClaw: QQBot admin commands could skip DM-only and allowFrom policy',
  'patched_version': '2026.4.29',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-rq6g-px6m-c248',
  'cve': 'CVE-2026-28469',
  'severity': 'HIGH',
  'cvss': 9.8,
  'title': 'OpenClaw Google Chat shared-path webhook target ambiguity allowed cross-account '
           'policy-context misrouting',
  'patched_version': '2026.2.14',
  'published': '2026-02-18'},
 {'ghsa': 'GHSA-7hxm-f538-3xp6',
  'cve': 'CVE-2026-53811',
  'severity': 'HIGH',
  'cvss': 8.8,
  'title': 'OpenClaw: Matrix allowFrom could bind to mutable display names',
  'patched_version': '2026.5.7',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-8wg3-5mcm-fjq8',
  'cve': 'CVE-2026-53819',
  'severity': 'HIGH',
  'cvss': 8.8,
  'title': 'OpenClaw: Workspace .env could override Homebrew executable selection for skill '
           'install flows',
  'patched_version': '2026.5.27',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-ffhm-8fwq-7q27',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 8.8,
  'title': 'Duplicate Advisory: OpenClaw: PowerShell encoded-command aliases could miss exec '
           'allowlist checks',
  'patched_version': '2026.5.12',
  'published': '2026-06-13'},
 {'ghsa': 'GHSA-g8p2-7wf7-98mq',
  'cve': 'CVE-2026-25253',
  'severity': 'HIGH',
  'cvss': 8.8,
  'title': 'OpenClaw/Clawdbot has 1-Click RCE via Authentication Token Exfiltration From '
           'gatewayUrl',
  'patched_version': '2026.1.29',
  'published': '2026-02-02'},
 {'ghsa': 'GHSA-hw9r-h9mr-4jff',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 8.8,
  'title': 'OpenClaw: Scoped chat.send route inheritance could bypass admin command scope gates',
  'patched_version': '2026.5.18',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-j472-gf56-x589',
  'cve': 'CVE-2026-53836',
  'severity': 'HIGH',
  'cvss': 8.8,
  'title': 'OpenClaw: PowerShell encoded-command aliases could miss exec allowlist checks',
  'patched_version': '2026.5.12',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-mc68-q9jw-2h3v',
  'cve': 'CVE-2026-24763',
  'severity': 'HIGH',
  'cvss': 8.8,
  'title': 'OpenClaw/Clawdbot Docker Execution has Authenticated Command Injection via PATH '
           'Environment Variable',
  'patched_version': '2026.1.29',
  'published': '2026-02-02'},
 {'ghsa': 'GHSA-q99w-vh6v-q3v7',
  'cve': 'CVE-2026-53843',
  'severity': 'HIGH',
  'cvss': 8.8,
  'title': 'OpenClaw: Pairing-scoped device session could restore revoked node token authority',
  'patched_version': '2026.5.26',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-qjpc-qf9m-xwmr',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 8.8,
  'title': 'OpenClaw: Trusted-proxy Control UI WebSocket accepted client-declared scopes before '
           'pairing',
  'patched_version': '2026.5.18',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-r2c6-8jc8-g32w',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 8.8,
  'title': 'Duplicate Advisory: 1-Click RCE via Authentication Token Exfiltration From gatewayUrl',
  'patched_version': '2026.1.29',
  'published': '2026-02-02'},
 {'ghsa': 'GHSA-v6r2-jh58-xx6w',
  'cve': 'CVE-2026-53810',
  'severity': 'HIGH',
  'cvss': 8.8,
  'title': "OpenClaw's marketplace runtime extension metadata could point at unscanned payloads",
  'patched_version': '2026.5.18',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-vxx3-6hc9-7cc3',
  'cve': 'CVE-2026-53806',
  'severity': 'HIGH',
  'cvss': 8.8,
  'title': 'OpenClaw: Combined POSIX shell options could confuse exec revalidation',
  'patched_version': '2026.5.12',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-w5ww-7chg-mxcq',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 8.8,
  'title': 'OpenClaw: Telegram interactive callbacks could skip commands.allowFrom',
  'patched_version': '2026.5.6',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-wrmq-9fc4-gwwj',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 8.8,
  'title': 'Duplicate Advisory: Pairing-scoped device session could restore revoked node token '
           'authority',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-2j8v-hwgc-x698',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 8.7,
  'title': 'OpenClaw: Shell wrapper argv could change between approval and execution',
  'patched_version': '2026.5.18',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-c29c-2q9c-pc86',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 8.6,
  'title': 'OpenClaw: Slack allowFrom could bind to mutable display names',
  'patched_version': '2026.5.3',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-6fvr-66p3-3qj4',
  'cve': 'CVE-2026-53814',
  'severity': 'HIGH',
  'cvss': 8.4,
  'title': 'OpenClaw: Hook-triggered CLI runs could receive owner MCP tool authority',
  'patched_version': '2026.5.20',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-3v3j-737j-7g74',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 8.3,
  'title': 'Duplicate Advisory: Linux and macOS exec allowlists skipped configured argument '
           'patterns',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-xr4f-mjxj-w6w5',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 8.3,
  'title': 'OpenClaw: Non-owner chat senders could issue device-pairing bootstrap codes',
  'patched_version': '2026.5.4',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-27pq-2ph8-8x25',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 8.1,
  'title': 'Duplicate Advisory: Shell positional parameters could weaken strict inline-eval checks',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-5cj2-3jr2-5h77',
  'cve': 'CVE-2026-53855',
  'severity': 'HIGH',
  'cvss': 8.1,
  'title': 'OpenClaw: Shell positional parameters could weaken strict inline-eval checks',
  'patched_version': '2026.4.2',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-8c59-hr4w-qg69',
  'cve': 'CVE-2026-53857',
  'severity': 'HIGH',
  'cvss': 8.1,
  'title': 'OpenClaw: Zalo allowFrom could bind to mutable display names',
  'patched_version': '2026.5.3',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-ccwh-wwpp-6wg5',
  'cve': 'CVE-2026-53864',
  'severity': 'HIGH',
  'cvss': 8.1,
  'title': 'OpenClaw: Host environment sanitizer missed two Node.js control variables',
  'patched_version': '2026.5.26',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-cw4q-gqg5-g38h',
  'cve': 'CVE-2026-53849',
  'severity': 'HIGH',
  'cvss': 8.1,
  'title': 'OpenClaw: Discord allowFrom could bind to mutable display names',
  'patched_version': '2026.5.7',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-f397-5vjw-v2c2',
  'cve': 'CVE-2026-53866',
  'severity': 'HIGH',
  'cvss': 8.1,
  'title': 'OpenClaw: Shell inline-command parsing could miss an allowlist check',
  'patched_version': '2026.5.12',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-p44v-rx83-vjp4',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 8.1,
  'title': 'Duplicate Advisory: Discord allowFrom could bind to mutable display names',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-v383-2wgg-v483',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 8.1,
  'title': 'Duplicate Advisory: Shell inline-command parsing could miss an allowlist check',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-vr6h-vxqj-3pjx',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 8.1,
  'title': 'Duplicate Advisory: Host environment sanitizer missed two Node.js control variables',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-w7m7-3xcf-mp48',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 8.1,
  'title': 'Duplicate Advisory: Zalo allowFrom could bind to mutable display names',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-chr9-m4q2-76hw',
  'cve': 'CVE-2026-53817',
  'severity': 'HIGH',
  'cvss': 8.0,
  'title': 'OpenClaw: Control UI locality spoofing could mint a durable admin device token',
  'patched_version': '2026.5.22',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-mgq6-vr84-7m2j',
  'cve': 'CVE-2026-35630',
  'severity': 'HIGH',
  'cvss': 8.0,
  'title': 'OpenClaw: QQBot native approval buttons did not enforce configured approver identity',
  'patched_version': '2026.5.18',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-xww8-gqvh-92x9',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 8.0,
  'title': 'OpenClaw: Exec approval display truncation could hide the command being approved',
  'patched_version': '2026.5.18',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-v8cx-933x-r976',
  'cve': 'CVE-2026-53813',
  'severity': 'HIGH',
  'cvss': 7.8,
  'title': 'OpenClaw: Fake package roots could influence memory-core artifact loading',
  'patched_version': '2026.4.25',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-3qg8-hq7j-jj33',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 7.7,
  'title': 'Duplicate Advisory: OpenClaw: Same-host trusted-proxy deployments could accept local '
           'forged identity headers',
  'patched_version': '2026.5.18',
  'published': '2026-06-13'},
 {'ghsa': 'GHSA-jvm4-4j77-39p6',
  'cve': 'CVE-2026-53833',
  'severity': 'HIGH',
  'cvss': 7.7,
  'title': 'OpenClaw: QQBot streaming command could mutate config without explicit allowFrom',
  'patched_version': '2026.4.29',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-q284-4pvr-m585',
  'cve': 'CVE-2026-25157',
  'severity': 'HIGH',
  'cvss': 7.7,
  'title': 'OpenClaw/Clawdbot has OS Command Injection via Project Root Path in sshNodeCommand',
  'patched_version': '2026.1.29',
  'published': '2026-02-02'},
 {'ghsa': 'GHSA-rggc-m335-3wvj',
  'cve': 'CVE-2026-53832',
  'severity': 'HIGH',
  'cvss': 7.7,
  'title': 'OpenClaw: Same-host trusted-proxy deployments could accept local forged identity '
           'headers',
  'patched_version': '2026.5.18',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-35c7-4r45-9gv3',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 7.5,
  'title': 'Duplicate Advisory: OpenClaw: QQBot pre-dispatch slash commands could skip allowFrom '
           'checks',
  'patched_version': '2026.4.27',
  'published': '2026-06-13'},
 {'ghsa': 'GHSA-77pv-3w4q-vrj5',
  'cve': 'CVE-2026-53834',
  'severity': 'HIGH',
  'cvss': 7.5,
  'title': 'OpenClaw: QQBot pre-dispatch slash commands could skip allowFrom checks',
  'patched_version': '2026.4.27',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-mr32-vwc2-5j6h',
  'cve': 'CVE-2026-28458',
  'severity': 'HIGH',
  'cvss': 7.5,
  'title': "OpenClaw's Browser Relay /cdp websocket is missing auth which could allow cross-tab "
           'cookie access',
  'patched_version': '2026.2.1',
  'published': '2026-02-17'},
 {'ghsa': 'GHSA-q447-rj3r-2cgh',
  'cve': 'CVE-2026-28478',
  'severity': 'HIGH',
  'cvss': 7.5,
  'title': 'OpenClaw affected by denial of service via unbounded webhook request body buffering',
  'patched_version': '2026.2.13',
  'published': '2026-02-18'},
 {'ghsa': 'GHSA-3c6j-hq33-3jv4',
  'cve': 'CVE-2026-53816',
  'severity': 'HIGH',
  'cvss': 7.2,
  'title': 'OpenClaw: Paired nodes could forge exec lifecycle events without system.run provenance',
  'patched_version': '2026.5.18',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-p73f-w79w-jqr5',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 7.2,
  'title': 'OpenClaw: Native command authorization could skip owner-command enforcement',
  'patched_version': '2026.5.6',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-24vr-rprv-67rf',
  'cve': 'CVE-2026-53846',
  'severity': 'HIGH',
  'cvss': 7.1,
  'title': 'OpenClaw: Workspace .env npm_execpath could influence bundled runtime dependency '
           'install',
  'patched_version': '2026.4.29',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-2w22-3f6x-3hf4',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 7.1,
  'title': 'Duplicate Advisory: Workspace-derived service PATH could influence trash command '
           'selection',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-3fqr-4cg8-h96q',
  'cve': 'CVE-2026-26317',
  'severity': 'HIGH',
  'cvss': 7.1,
  'title': 'OpenClaw affected by cross-site request forgery (CSRF) through loopback browser '
           'mutation endpoints',
  'patched_version': '2026.2.14',
  'published': '2026-02-18'},
 {'ghsa': 'GHSA-4qgr-57jq-93vh',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 7.1,
  'title': 'Duplicate Advisory: Workspace .env STATE_DIRECTORY could influence bundled runtime '
           'dependency roots',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-77q5-rr5v-x43q',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 7.1,
  'title': 'OpenClaw: Trusted retry endpoint checks could match hostname prefixes',
  'patched_version': '2026.5.7',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-9fr2-p65v-gqxq',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 7.1,
  'title': 'Duplicate Advisory: Workspace .env CLOUDSDK_PYTHON could influence Gmail setup gcloud '
           'execution',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-fq9j-vw4w-fr6v',
  'cve': 'CVE-2026-53842',
  'severity': 'HIGH',
  'cvss': 7.1,
  'title': 'OpenClaw: Workspace .env CLOUDSDK_PYTHON could influence Gmail setup gcloud execution',
  'patched_version': '2026.5.2',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-mhq8-78pj-5j79',
  'cve': 'CVE-2026-53831',
  'severity': 'HIGH',
  'cvss': 7.1,
  'title': "OpenClaw's POSIX node system.run safe-bin allowlist could be widened by shell "
           'expansion',
  'patched_version': '2026.5.18',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-qp5j-jr73-m2pw',
  'cve': None,
  'severity': 'HIGH',
  'cvss': 7.1,
  'title': 'Duplicate Advisory: Workspace .env npm_execpath could influence bundled runtime '
           'dependency install',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-rjxq-qqhf-8hwh',
  'cve': 'CVE-2026-53840',
  'severity': 'HIGH',
  'cvss': 7.1,
  'title': 'OpenClaw: MCP Streamable HTTP redirects could forward configured custom headers to '
           'another origin',
  'patched_version': '2026.5.12',
  'published': '2026-06-17'},
 {'ghsa': 'GHSA-rx78-29qr-5hq8',
  'cve': 'CVE-2026-53865',
  'severity': 'HIGH',
  'cvss': 7.1,
  'title': 'OpenClaw: Workspace-derived service PATH could influence trash command selection',
  'patched_version': '2026.5.2',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-v2ww-5rh7-2h5v',
  'cve': 'CVE-2026-53853',
  'severity': 'HIGH',
  'cvss': 7.1,
  'title': 'OpenClaw: Linux and macOS exec allowlists skipped configured argument patterns',
  'patched_version': '2026.5.12',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-wc84-j36w-pw4x',
  'cve': 'CVE-2026-53858',
  'severity': 'HIGH',
  'cvss': 7.1,
  'title': 'OpenClaw: Workspace .env STATE_DIRECTORY could influence bundled runtime dependency '
           'roots',
  'patched_version': '2026.5.2',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-q7q8-3mgw-q67r',
  'cve': 'CVE-2026-53815',
  'severity': 'HIGH',
  'cvss': 6.5,
  'title': 'OpenClaw: Message read actions could skip channel allowlist checks',
  'patched_version': '2026.5.19',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-6xcg-6q43-rj2v',
  'cve': None,
  'severity': 'LOW',
  'cvss': 6.1,
  'title': 'Duplicate Advisory: Exported session HTML could keep unsafe markdown links',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-8mg9-j9cf-54cj',
  'cve': 'CVE-2026-53852',
  'severity': 'LOW',
  'cvss': 5.4,
  'title': 'OpenClaw: Empty-scope device re-pairing could confuse caller scope containment',
  'patched_version': '2026.4.25',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-hc4w-hm59-9w88',
  'cve': None,
  'severity': 'LOW',
  'cvss': 5.4,
  'title': 'Duplicate Advisory: Empty-scope device re-pairing could confuse caller scope '
           'containment',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-68xw-r643-9p5w',
  'cve': 'CVE-2026-53845',
  'severity': 'LOW',
  'cvss': 4.3,
  'title': 'OpenClaw: Skill-command dispatch could skip before-tool-call hooks',
  'patched_version': '2026.5.6',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-cwpp-5962-q4f6',
  'cve': 'CVE-2026-53848',
  'severity': 'LOW',
  'cvss': 4.3,
  'title': 'OpenClaw: Exec allowlist could miss side effects from transparent command wrappers',
  'patched_version': '2026.5.26',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-r7vv-6763-m739',
  'cve': None,
  'severity': 'LOW',
  'cvss': 4.3,
  'title': 'Duplicate Advisory: Skill-command dispatch could skip before-tool-call hooks',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-wrr6-p5r6-474m',
  'cve': None,
  'severity': 'LOW',
  'cvss': 4.3,
  'title': 'Duplicate Advisory: Exec allowlist could miss side effects from transparent command '
           'wrappers',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-8hj2-w4c9-fjfq',
  'cve': None,
  'severity': 'LOW',
  'cvss': 4.2,
  'title': 'Duplicate Advisory: BlueBubbles sender policy could match mutable conversation '
           'identifiers',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-8j37-5w68-wj2g',
  'cve': 'CVE-2026-53860',
  'severity': 'LOW',
  'cvss': 4.2,
  'title': 'OpenClaw: BlueBubbles sender policy could match mutable conversation identifiers',
  'patched_version': '2026.5.7',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-9v8j-9c9g-w66c',
  'cve': 'CVE-2026-53862',
  'severity': 'LOW',
  'cvss': 4.2,
  'title': 'OpenClaw: Bootstrap token replay could widen pending pairing scopes',
  'patched_version': '2026.5.12',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-h9h6-pwqv-j9hv',
  'cve': None,
  'severity': 'LOW',
  'cvss': 4.2,
  'title': 'Duplicate Advisory: Bootstrap token replay could widen pending pairing scopes',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-3wqp-prf6-2m72',
  'cve': None,
  'severity': 'LOW',
  'cvss': 3.1,
  'title': 'OpenClaw: Feishu dynamic-agent bindings could miss configWrites enforcement',
  'patched_version': '2026.5.6',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-chm2-m3w2-wcxm',
  'cve': None,
  'severity': 'LOW',
  'cvss': 2.1,
  'title': 'OpenClaw Google Chat spoofing access with allowlist authorized mutable email principal '
           'despite sender-ID mismatch',
  'patched_version': '2026.2.14',
  'published': '2026-02-17'},
 {'ghsa': 'GHSA-83w9-h5wv-j9xm',
  'cve': 'CVE-2026-53838',
  'severity': 'MEDIUM',
  'cvss': 9.8,
  'title': 'OpenClaw: Node pairing reconnection could confuse approval scope state',
  'patched_version': '2026.5.27',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-c85p-9pvr-f7f5',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 9.8,
  'title': 'Duplicate Advisory: OpenClaw: Node pairing reconnection could confuse approval scope '
           'state',
  'patched_version': '2026.5.27',
  'published': '2026-06-13'},
 {'ghsa': 'GHSA-2hfg-4fh4-qp7f',
  'cve': 'CVE-2026-53812',
  'severity': 'MEDIUM',
  'cvss': 7.7,
  'title': "OpenClaw's browser act interactions could bypass private-network navigation checks",
  'patched_version': '2026.5.18',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-8wmm-344f-mpjg',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 7.1,
  'title': 'Duplicate Advisory: Tool group policy callers could accept unvalidated group IDs',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-x7cf-6gp3-q5f8',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 7.1,
  'title': 'Duplicate Advisory: MCP Streamable HTTP redirects could forward configured custom '
           'headers to another origin',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-qh2f-99mv-mrcf',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 6.9,
  'title': 'OpenClaw: Bundle MCP loopback could miss its exec denylist on session spawn',
  'patched_version': '2026.5.12',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-grc3-2j34-p6gm',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 6.8,
  'title': 'OpenClaw: message.action forwarding could send Gateway credentials to model-supplied '
           'loopback URLs',
  'patched_version': '2026.5.2',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-mpc8-jxjh-qpgh',
  'cve': 'CVE-2026-53850',
  'severity': 'MEDIUM',
  'cvss': 6.8,
  'title': 'OpenClaw: Focus command could miss controlScope enforcement',
  'patched_version': '2026.4.25',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-c226-q6fx-6j6c',
  'cve': 'CVE-2026-53861',
  'severity': 'MEDIUM',
  'cvss': 6.6,
  'title': 'OpenClaw: macOS Swift exec allowlist missed combined POSIX inline flags',
  'patched_version': '2026.5.6',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-g796-jqmx-wf9q',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 6.6,
  'title': 'Duplicate Advisory: macOS Swift exec allowlist missed combined POSIX inline flags',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-rj6p-xmxr-qj4h',
  'cve': 'CVE-2026-53818',
  'severity': 'MEDIUM',
  'cvss': 6.6,
  'title': 'OpenClaw: MCP loopback could skip owner-only tool policy for non-owner callers',
  'patched_version': '2026.4.24',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-275c-xpvc-jgfw',
  'cve': 'CVE-2026-53830',
  'severity': 'MEDIUM',
  'cvss': 6.5,
  'title': 'OpenClaw: Slack and Zalo webhook secrets could remain active after secrets.reload',
  'patched_version': '2026.4.22',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-6jm4-83g2-35gv',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 6.5,
  'title': 'Duplicate Advisory: memory-wiki shared search could miss session visibility checks',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-72fw-cqh5-f324',
  'cve': 'CVE-2026-53844',
  'severity': 'MEDIUM',
  'cvss': 6.5,
  'title': 'OpenClaw: memory-wiki shared search could miss session visibility checks',
  'patched_version': '2026.4.29',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-9c3v-684m-579c',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 6.5,
  'title': 'OpenClaw MCP SSE redirects could forward Authorization headers',
  'patched_version': '2026.6.5',
  'published': '2026-07-01'},
 {'ghsa': 'GHSA-g34w-4xqq-h79m',
  'cve': 'CVE-2026-26328',
  'severity': 'MEDIUM',
  'cvss': 6.5,
  'title': 'OpenClaw iMessage group allowlist authorization inherited DM pairing-store identities',
  'patched_version': '2026.2.14',
  'published': '2026-02-18'},
 {'ghsa': 'GHSA-gxg4-2rrr-jhc7',
  'cve': 'CVE-2026-53859',
  'severity': 'MEDIUM',
  'cvss': 6.5,
  'title': 'OpenClaw: Hostname checks could treat trailing-dot hosts inconsistently',
  'patched_version': '2026.5.26',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-h89v-j3x9-8wqj',
  'cve': 'CVE-2026-28452',
  'severity': 'MEDIUM',
  'cvss': 6.5,
  'title': 'OpenClaw affected by denial of service through unguarded archive extraction allowing '
           'high expansion/resource abuse (ZIP/TAR)',
  'patched_version': '2026.2.14',
  'published': '2026-02-18'},
 {'ghsa': 'GHSA-hcm3-8f6r-6xwg',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 6.5,
  'title': 'OpenClaw: Browser debug/export routes could reuse already-open blocked tabs',
  'patched_version': '2026.4.29',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-p2fh-f5fc-44hr',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 6.5,
  'title': 'OpenClaw: memory-wiki ingest could read local files with operator.write scope',
  'patched_version': '2026.5.12',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-r2fx-hp6p-pgrm',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 6.5,
  'title': 'Duplicate Advisory: Internal/webchat command auth could inherit ownerAllowFrom '
           'wildcard state',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-vqx6-6j84-2794',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 6.5,
  'title': 'Duplicate Advisory: Hostname checks could treat trailing-dot hosts inconsistently',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-4m3v-q747-pc6h',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 6.3,
  'title': 'OpenClaw: Mattermost slash token revocation could lag until monitor refresh',
  'patched_version': '2026.4.24',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-w9hf-3pp7-pvxv',
  'cve': 'CVE-2026-53841',
  'severity': 'MEDIUM',
  'cvss': 6.1,
  'title': 'OpenClaw: Exported session HTML could keep unsafe markdown links',
  'patched_version': '2026.5.12',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-4hpg-mp64-x7xq',
  'cve': 'CVE-2026-53854',
  'severity': 'MEDIUM',
  'cvss': 6.0,
  'title': 'OpenClaw: Internal/webchat command auth could inherit ownerAllowFrom wildcard state',
  'patched_version': '2026.4.25',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-985f-72mj-8gf7',
  'cve': 'CVE-2026-53863',
  'severity': 'MEDIUM',
  'cvss': 6.0,
  'title': 'OpenClaw: Tool group policy callers could accept unvalidated group IDs',
  'patched_version': '2026.4.25',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-mj5r-hh7j-4gxf',
  'cve': 'CVE-2026-28480',
  'severity': 'MEDIUM',
  'cvss': 5.9,
  'title': 'OpenClaw Telegram allowlist authorization accepted mutable usernames',
  'patched_version': '2026.2.14',
  'published': '2026-02-18'},
 {'ghsa': 'GHSA-gw2c-6hcg-5g52',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 5.5,
  'title': 'Duplicate Advisory: Focus command could miss controlScope enforcement',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-rwp6-7w3q-75fq',
  'cve': 'CVE-2026-53856',
  'severity': 'MEDIUM',
  'cvss': 5.5,
  'title': 'OpenClaw: Config recovery could restore openclaw.json with broad file permissions',
  'patched_version': '2026.4.24',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-vqj9-vhg4-27mg',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 5.5,
  'title': 'Duplicate Advisory: Config recovery could restore openclaw.json with broad file '
           'permissions',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-w2cg-vxx6-5xjg',
  'cve': 'CVE-2026-29612',
  'severity': 'MEDIUM',
  'cvss': 5.5,
  'title': 'OpenClaw: denial of service through large base64 media files allocating large buffers '
           'before limit checks',
  'patched_version': '2026.2.14',
  'published': '2026-02-18'},
 {'ghsa': 'GHSA-58wc-8wrv-xp9j',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 5.4,
  'title': 'Duplicate Advisory: Active Memory write scope could mutate global config',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-6c4r-g249-wv3c',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 5.3,
  'title': 'OpenClaw: Sandboxed session spawn could expose the real workspace path to child '
           'prompts',
  'patched_version': '2026.4.26',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-c8w7-9w9h-x69q',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 5.3,
  'title': 'Duplicate Advisory: Slack reaction events could ignore reaction notification settings',
  'patched_version': None,
  'published': '2026-06-16'},
 {'ghsa': 'GHSA-cqwv-9qjx-vxw2',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 5.3,
  'title': 'OpenClaw: Skill Workshop apply flow could override pending approval',
  'patched_version': '2026.5.6',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-fcvx-5cxc-v5p8',
  'cve': 'CVE-2026-53851',
  'severity': 'MEDIUM',
  'cvss': 5.3,
  'title': 'OpenClaw: Slack reaction events could ignore reaction notification settings',
  'patched_version': '2026.5.12',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-x629-46cc-7xgw',
  'cve': 'CVE-2026-53847',
  'severity': 'MEDIUM',
  'cvss': 5.3,
  'title': 'OpenClaw: Active Memory write scope could mutate global config',
  'patched_version': '2026.5.6',
  'published': '2026-06-18'},
 {'ghsa': 'GHSA-p39j-x9h5-q66m',
  'cve': 'CVE-2026-53809',
  'severity': 'MEDIUM',
  'cvss': 3.8,
  'title': 'OpenClaw: Embedded runner policy could be confused by provider aliases',
  'patched_version': '2026.4.25',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-chqm-wxm2-w73w',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 3.7,
  'title': 'Duplicate Advisory: OpenClaw: Mattermost handlers could fall open when channel type '
           'was missing',
  'patched_version': '2026.5.6',
  'published': '2026-06-13'},
 {'ghsa': 'GHSA-gp79-m99v-gjmh',
  'cve': 'CVE-2026-53837',
  'severity': 'MEDIUM',
  'cvss': 3.7,
  'title': 'OpenClaw: Mattermost handlers could fall open when channel type was missing',
  'patched_version': '2026.5.6',
  'published': '2026-07-02'},
 {'ghsa': 'GHSA-wv26-j37q-2g7p',
  'cve': None,
  'severity': 'MEDIUM',
  'cvss': 0.0,
  'title': "OpenClaw's Slack plugin approvals used the exec approver gate for plugin actions",
  'patched_version': '2026.5.12',
  'published': '2026-07-02'}]
